### ISSUE TITLE
Picture + Symbols

### ISSUE THREAD

**Issue by el-j** [myles-systems/myles-systems.github.io#1]
Wir brauchen die (hintergrund)-Bilder und Symbole als Graphiken in voller Auflösung.
Die Graphiken + Bilder bitte in im Ordner  img mit entsprechendem Namen austauschen.

Symbole würde ich gern als svg einbinden. also bitte mit transparentem Hintergrund
als svg tiny 1.1 exportieren. 

und im ordner img/symbols ablegen.

**Comment by davidgoepfert** [comment]
![bildschirmfoto 2016-11-19 um 19 06 26](https://cloud.githubusercontent.com/assets/8558361/20457416/4cbfa09a-ae8b-11e6-886e-a4a5b8ef32d0.png)
![bildschirmfoto 2016-11-19 um 19 06 06](https://cloud.githubusercontent.com/assets/8558361/20457420/4cc323d2-ae8b-11e6-8fef-0aaeaeda4373.png)
![bildschirmfoto 2016-11-19 um 19 06 21](https://cloud.githubusercontent.com/assets/8558361/20457417/4cbf8e70-ae8b-11e6-8e59-ddd76ad442e5.png)
![bildschirmfoto 2016-11-19 um 19 06 17](https://cloud.githubusercontent.com/assets/8558361/20457418/4cbfa9b4-ae8b-11e6-931e-4f172de057f3.png)
![bildschirmfoto 2016-11-19 um 19 06 12](https://cloud.githubusercontent.com/assets/8558361/20457419/4cc1020a-ae8b-11e6-8a37-53b689510cc8.png)

**Comment by davidgoepfert** [comment]
Ich hab alle Icons hinzugefügt und einen Folder für icons unter /images angelegt.
