### ISSUE TITLE
Langdingpage Navigation/Section wording

### ISSUE THREAD

**Issue by el-j** [myles-systems/myles-systems.github.io#2]
Wir haben in der Navigation die punkte:  
- Home 
- Get Beta
- FAQ
- Blog
- Contact

Eigentlich sollten diese Punkte zu bestimmten abschnitten der seite führen. 
Wie sollen diese Abschnitte benannt werden?

**Comment by paulvollmer** [comment]
ich bin für die benennung der divs, also
- os
- control
- analytics
- ...

Home, Get Beta und Blog brauchen wir meiner meinung erstmal nicht und ich denke das ist platzhalter von dave. @davidgoepfert korrekt?

**Comment by davidgoepfert** [comment]
Wir kommen für erste Release ohne Navi aus. Das können wir später ergänzen.
