### ISSUE TITLE
Bugliste

### ISSUE THREAD

**Issue by davidgoepfert** [myles-systems/myles-systems.github.io#9]

**Comment by davidgoepfert** [comment]
![bildschirmfoto 2016-11-19 um 19 28 09](https://cloud.githubusercontent.com/assets/8558361/20457557/5b3cd2ca-ae8e-11e6-93eb-19cd351abb37.png)

**Comment by davidgoepfert** [comment]
<img width="1173" alt="bildschirmfoto 2017-02-15 um 13 23 59" src="https://cloud.githubusercontent.com/assets/8558361/22974320/0e332676-f382-11e6-8829-c02003139d49.png">

Etwas Abstand zwischen den Spalten einsetzen…

**Comment by el-j** [comment]
Ok also die letzten pushs haben die bugs soweit beseitigt. 
bei mir sieht alles schick aus. die preview videos zeigen das entsprechend.

gibt es noch weitere bugs??? anderenfalls würd ich dann online gehen ...

[Preview Desktop Styling](https://drive.google.com/open?id=0By1pjKSYE4UkajJvTDBfWDgyUjA)
[Preview Mobil Styling](https://drive.google.com/open?id=0By1pjKSYE4Ukd0lFalZ1cTRRcm8)

**Comment by davidgoepfert** [comment]
Super! Sieht schon viel besser aus…

Bitte noch folgendes bearbeiten:

<img width="1117" alt="bildschirmfoto 2017-04-13 um 11 39 28" src="https://cloud.githubusercontent.com/assets/8558361/24999536/292f911a-203e-11e7-8c8b-39ce937dfdda.png">

Das rutsch bei mir (Firefox MAC) etwas komisch zusammen:
<img width="1169" alt="bildschirmfoto 2017-04-13 um 11 39 35" src="https://cloud.githubusercontent.com/assets/8558361/24999568/567854d6-203e-11e7-9bc3-2731585c320c.png">

Anmerkung: Die Social-Links können zusammen in einem Block stehen, link daneben dann Impressum.

**Comment by davidgoepfert** [comment]
Impressumsangaben: Ich bräuchte dafür eurer Steuernummern inkl. Handels-Registereintrag. Dann ist das auch fertig…

<img width="691" alt="bildschirmfoto 2017-04-13 um 11 44 19" src="https://cloud.githubusercontent.com/assets/8558361/24999637/a326c5d8-203e-11e7-923c-83124f1f19d8.png">

myles.systems GbR
Fachhochschule Potsdam 
Friedrich-Ebert-Str. 4
14467 Potsdam

Gesellschafter: Paul Vollmer, Fabian Althaus, David Göpfert

E-Mail: hallo@myles.systems

Umsatzsteuer-Identifikationsnummer gem. § 27a UStG: DE 123456789
Inhaltlich Verantwortlicher gem. § 55 II RStV: Maximilian Mustermann (Anschrift s.o.)(1)

Quelle:
http://www.impressum-recht.de/gbr-muster-impressum.html

**Comment by davidgoepfert** [comment]
<img width="1100" alt="bildschirmfoto 2017-04-13 um 11 45 23" src="https://cloud.githubusercontent.com/assets/8558361/24999707/e885a414-203e-11e7-96fb-ee2dca30eb54.png">

Analytics ist noch nicht fertig: @paulvollmer meinte, dass es im Diagram einen regelmässigen Verlauf geben müsste (also jeden Tag neustart, Runterfahren usw. = Muster ) diese Vis müssten mit ins Diagram.

@paulvollmer wollte dazu eine Version anlegen (ai. vorhanden). Das kann dann animiert werden.

**Comment by davidgoepfert** [comment]
@el-j : es gib auch noch eine Seite names IMPRESSUM, deine Änderungen musst du auch dort machen …

**Comment by davidgoepfert** [comment]
@paulvollmer : kommt noch ein Statistik-Screen von dir?

**Comment by el-j** [comment]
dafür musst du einen anker machen. 
siehe: https://wiki.selfhtml.org/wiki/HTML/Regeln/Seiteninterne_Verweise

**Comment by davidgoepfert** [comment]
Ich kann leider unseren Domainhoster für myles.systems nicht finden… Weiss wer, wo wir unsere Domain hosten? Ich würde gern email-adressen anlegen:

fa@myles.systems
pv@myles.systems
dg@myles.systems
